$index = "c:\Users\norma\Downloads\Arcana\Arcana\index.html"
$productos = "c:\Users\norma\Downloads\Arcana\Arcana\productos.html"
$style = "c:\Users\norma\Downloads\Arcana\Arcana\style.css"

$txt = [System.IO.File]::ReadAllText($index)
$txt = $txt.Replace('<a href="productos.html" button class="cta-btn">', '<a href="productos.html" class="cta-btn">')
$txt = $txt.Replace('calidad y garantia', 'Calidad y garantía')
$txt = $txt.Replace('¿por qué comprar', '¿Por qué comprar')
$txt = $txt.Replace('<h3> contamos con', '<h3> Contamos con')
$txt = $txt.Replace('garantia de 25', 'garantía de 25')
$txt = $txt.Replace('<h3> ahorro de', '<h3> Ahorro de')
$txt = $txt.Replace('las paginas oficiales', 'las páginas oficiales')
$txt = $txt.Replace('<h2> servicios en venta', '<h2> Servicios en venta')
$txt = $txt.Replace('servicio amplio', 'Servicio amplio')
$txt = $txt.Replace('contamos con cuentas', 'Contamos con cuentas')
$txt = $txt.Replace('desde el plan', 'Desde el plan')
$txt = $txt.Replace('se creo con', 'se creó con')
$txt = $txt.Replace('esta pagina web', 'esta página web')
$txt = $txt.Replace('<h3>links</h3>', '<h3>Links</h3>')
$txt = $txt.Replace('<h3> contactos </h3>', '<h3> Contactos </h3>')
$txt = $txt.Replace('a traves de', 'a través de')
$txt = $txt.Replace('-instagram', '- Instagram')
$txt = $txt.Replace('-grupo de whatsapp', '- Grupo de WhatsApp')
$txt = $txt.Replace('-Facebook', '- Facebook')
$txt = $txt.Replace('unete al grupo', 'Únete al grupo')
$txt = $txt.Replace('Dueño de la pagina:', 'Dueño de la página:')
$txt = $txt.Replace('sub-dueño:', 'Sub-dueño:')
[System.IO.File]::WriteAllText($index, $txt)

$txt2 = [System.IO.File]::ReadAllText($productos)
$txt2 = $txt2 -replace '(?m)^\s*\|\s*$', ''
$txt2 = $txt2.Replace('se creo con', 'se creó con')
$txt2 = $txt2.Replace('esta pagina web', 'esta página web')
$txt2 = $txt2.Replace('<h3>links</h3>', '<h3>Links</h3>')
$txt2 = $txt2.Replace('<h3> Contactos </h3>', '<h3> Contactos </h3>')
$txt2 = $txt2.Replace('a traves de', 'a través de')
$txt2 = $txt2.Replace('-Instagram', '- Instagram')
$txt2 = $txt2.Replace('-Grupo de whatsapp', '- Grupo de WhatsApp')
$txt2 = $txt2.Replace('-Facebook', '- Facebook')
$txt2 = $txt2.Replace('Unete al grupo', 'Únete al grupo')
$txt2 = $txt2.Replace('Dueño de la pagina:', 'Dueño de la página:')
$txt2 = $txt2.Replace('Sub-dueño:', 'Sub-dueño:')
[System.IO.File]::WriteAllText($productos, $txt2)

$txt3 = [System.IO.File]::ReadAllText($style)
$txt3 = $txt3.Replace('letas de bienvenida', 'letras de bienvenida')
[System.IO.File]::WriteAllText($style, $txt3)
