INSERT INTO products (name, description, category, image_url) VALUES 
('Disney+', 'Acceso a un perfil de Disney.', 'perfil', 'Disney.jpg'),
('Max Platino', 'Acceso a un perfil de Max Platino.', 'perfil', 'HBO.png'),
('Prime Video - Perfil', 'Perfil S/A (Sin Anuncios).', 'perfil', 'Prime.png'),
('YouTube Premium - Perfil', 'Membresía por invitación a tu correo.', 'perfil', 'premiumYT.jpg'),
('Crunchyroll - Perfil', 'Perfil para ver el mejor anime.', 'perfil', 'crunchyroll.jpg'),
('Universal+ - Perfil', 'Perfil individual para contenido Universal.', 'perfil', 'universal.jpg'),
('ChatGPT Plus', 'Acceso a ChatGPT Plus (IA Avanzada).', 'perfil', 'chatgpt.png'),
('Max Platino - Completa', 'Cuenta completa con los mejores beneficios de Max.', 'completa', 'HBO.png'),
('Prime Video - Completa', 'Disfruta de la cuenta entera para ti.', 'completa', 'Prime.png'),
('Crunchyroll - Completa', 'Anime sin límites, cuenta completa.', 'completa', 'crunchyroll.jpg'),
('YouTube Premium (Familiar)', 'Cuenta completa familiar.', 'completa', 'premiumYT.jpg'),
('IPTV - Completa', 'Televisión, películas y series en vivo.', 'completa', 'IPTV.jpg'),
('Vix+ - Completa', 'Todo el contenido de Vix sin restricciones.', 'completa', 'vix.jpg'),
('Smartfit planes', 'Planes desde básico a Black.', 'smartfit', 'Smartfit_plan.jpg'),
('Canva Pro', 'Cuentas de Canva Pro de 1 mes o más', 'canva', 'CanvaPro.jpg'),
('Super Duolingo', '¡También contamos con Duolingo!', 'duolingo', 'SuperDuolingo.jpg'),
('Recargas telefónicas', 'Recargas de teléfono de Telcel y Bait', 'recargas', 'RecargasTelefono.png'),
('Seguidores/Fw', 'Servicio de seguidores para TikTok e Instagram', 'seguidores', 'Tiktok_Instagram.png');
